### ISSUE TITLE
Problem with Arducam for Jetson Nano with L4T 32.5.1 

### ISSUE THREAD

**Issue by ahtabrizi** [ArduCAM/MIPI_Camera#119]
I’m trying to install Arducam camera drivers on jetson nano with L4T 32.5.1 (4.9.201-tegra kernel) using the script provided by [this link](https://www.arducam.com/docs/camera-for-jetson-nano/mipi-camera-modules-for-jetson-nano/driver-installation/).
After I reboot, I get stuck in the boot and cannot proceed. Almost no command works and there seem to be lots of system files missing. This is what I see after I reboot:

![WhatsApp Image 2021-06-02 at 18 17 25](https://user-images.githubusercontent.com/46006573/120508578-16a47f00-c3dd-11eb-9f1e-5fbb832c112b.jpeg)

What should I do to fix this driver and get the camera working without messing up anything?

**Comment by glddiv** [comment]
Replied here:
https://www.arducam.com/forums/topic/problem-with-arducam-for-jetson-nano-with-l4t-32-5-1/
