### ISSUE TITLE
Preview video from Stereo Camera Hat is really DARK

### ISSUE THREAD

**Issue by openedhardware** [ArduCAM/MIPI_Camera#22]
I am using RPi4 & Stereo Camera Hat.

I've tried `./arducamstill -t 0 -m 10 -awb 1 -ae 1`, but the preview video is pretty dark:
![IMG_20200214_184533](https://user-images.githubusercontent.com/16890683/74576876-caef7b80-4fc7-11ea-85e6-860035359b57.jpg)
If I increase the brightness, it turns yellow...
Anything I can do to get normal video feed?

**Comment by openedhardware** [comment]
Here is my current setup:
![IMG_20200214_180621](https://user-images.githubusercontent.com/16890683/74576946-05f1af00-4fc8-11ea-9dfa-b64ac5f713b0.jpg)

**Comment by ArduCAM** [comment]
@openedhardware 
The arducamstill is using our MIPI camera driver which is receiving RAW data from the camera without any ISP processing, you can directly access the sensor exposure register to increase the exposure speed.
Or you can try to use the raspistill command which using Raspberry pi official camera driver to try it out.

**Comment by openedhardware** [comment]
@ArduCAM 
Hmm, so can I use `raspistill` command to use the official camera driver?
Here is the output:
```
pi@raspberrypi:~ $ raspistill -o 1.jpg
Camera control callback  cmd=0x4f525245mmal: No data received from sensor. Check all connections, including the Sunny one on the camera board
^Cmmal: Aborting program
```
What do you think?

**Comment by ArduCAM** [comment]
Have you done a cold reboot for the hardware?
After run the arducamstill the board register might be changed, so you need to power down to restore the default settings for raspistill command

**Comment by openedhardware** [comment]
@ArduCAM 
Yeah, of course. I had rebooted several times.

**Comment by ArduCAM** [comment]
can you setup a remote TeamViewer for debugging?

**Comment by openedhardware** [comment]
@ArduCAM 
Please let me know what I have to do for debugging..

**Comment by arnolde** [comment]
@openedhardware Could you please let us know how you solved this? I have the same problem currently. Thanks!
