### ISSUE TITLE
preview-camera0 SegmentationFault on CM3+ devkit

### ISSUE THREAD

**Issue by sinaaghli** [ArduCAM/MIPI_Camera#34]
Running preview-camera0 executable gives

> Open camera...
> segfault

On CM3+ dev-kit and OV7251 camera?

I have followed the steps [here](https://www.raspberrypi.org/documentation/hardware/computemodule/cmio-camera.md) Are there any other steps to take other than what has been mentioned in this link?

**Comment by fuzzybear62** [comment]
Try an older version. for sure April 24th works on CM3+

**Comment by sinaaghli** [comment]
Thank you for the quick response, that worked.

**Comment by sinaaghli** [comment]
following commit has fixed the issue
b15b5346685f07c66f2d2420f1af2fa92c19cab9
