### ISSUE TITLE
Segmentation Fault. Failed to asign 39238144 bytes of shared memory

### ISSUE THREAD

**Issue by zainmehdi** [ArduCAM/MIPI_Camera#35]
Hi I have been trying to use B0163 13MP camera with my raspberry pi 4. Whenever I try to capture an image using capture exe with mode 4 ( width 4192, height : 3120) I get segmentation fault. Is there anything I am missing here ?

Thanks

**Comment by ArduCAM** [comment]
Our engineer is discussing the problem here https://www.arducam.com/forums/topic/segmentation-fault-failed-to-asign-39238144-bytes-of-shared-memory/
