### ISSUE TITLE
Arducam Still doenst open Preview

### ISSUE THREAD

**Issue by m4us1ne** [ArduCAM/MIPI_Camera#62]
followed the installation instructions and taking pictures seems to work, but none of the tools displays a preview video (no errors shown in cosole).
host is raspberry pi 3 b+

**Comment by m4us1ne** [comment]
problem was the remotedesktop connection.

**Comment by bburns** [comment]
How did you fix it? I'm using VNC on a Mac and haven't been able to get preview to work either.

**Comment by m4us1ne** [comment]
sry for the late answer, i connected the pi directly with an hdmi cable
