### ISSUE TITLE
Where is the source for the Jetson HQ Camera driver?

### ISSUE THREAD

**Issue by mdegans** [ArduCAM/MIPI_Camera#66]
The RidgeRun driver used is GPL licensed. Please provide the source along with the binary packages.

**Comment by glddiv** [comment]
Hi @mdegans ,
We compiled the source code of [NVIDIA-Jetson-IMX477-RPIV3](https://github.com/RidgeRun/NVIDIA-Jetson-IMX477-RPIV3) to generate a binary file for easy use, and provided a link to the source code in the README.

**Comment by mdegans** [comment]
Thanks, @glddiv , I missed that.
