### ISSUE TITLE
driver doesnt work with raspberry 4 / new python library

### ISSUE THREAD

**Issue by hstarmans** [ArduCAM/MIPI_Camera#85]
The MIPI_camera leads to system kernel crashes on the raspberry 4. This can be mitigated by moving back to raspberry 3B
I have also created an example of a new python library for [Arducam](https://github.com/hstarmans/Arducampython).
This could be an example for the author @ArduCAM , on how to create a python library.
If your reading this, improve your C driver. If it fails, it kills the whole linux kernel and i need to reboot.
Secondly, clean up the repo. It takes a lot of time to download as you reupload new binaries all the time and push this into git.
Git is intended for text files, not for binaries.
I do like the project, however.

**Comment by glddiv** [comment]
Hi @hstarmans 

> The MIPI_camera leads to system kernel crashes on the raspberry 4. This can be mitigated by moving back to raspberry 3B

Thank you for your feedback. What camera are you using? We will run the test.

> I have also created an example of a new python library for Arducam.
This could be an example for the author @ArduCAM , on how to create a python library.

Thanks for the code. Initially we also considered packaging methods such as cython or pybinding, but for some reason, we chose ctypes. Your code can be a good start. thanks again.

> Secondly, clean up the repo. It takes a lot of time to download as you reupload new binaries all the time and push this into git.
Git is intended for text files, not for binaries.

We have also noticed this problem. Due to historical problems, many links in videos and documents point to this  repository. If we clean up, we will encounter some resistance.

> I do like the project, however.

Glad to hear that you like it, please let us know if you have any comments or suggestions.

**Comment by glddiv** [comment]
Hi @hstarmans 
By the way, can you provide relevant error information? We don't seem to notice this problem.

**Comment by hstarmans** [comment]
On the raspberry pi3b it works. On the raspberry pi 4, I have however;
```pi@raspberrypi:~/MIPI_Camera/RPI $ ./list_format
Found sensor ov2311 at address 60
```
Hereafter the systems crashes. This is not the case for the Raspberry pi3B.
Output of i2c detect. Note, that I modified wiringpi as it gave an issue.
```
setting GPIO for board revsion: d03114
Raspberry Pi3B / Pi3B+ / 3A / 4B(1G/2G/4G)
Set state of 133 to 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: 60 -- -- -- -- -- -- -- -- -- -- -- 6c -- -- --
70: 70 -- -- -- -- -- -- --
```


Network error: Connection timed out

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Session stopped
    - Press <return> to exit tab
    - Press R to restart session
    - Press S to save terminal output to file
     ┌────────────────────────────────────────────────────────────────────┐
     │                        • MobaXterm 20.6 •                          │
     │            (SSH client, X-server and networking tools)             │
     │                                                                    │
     │ ➤ SSH session to pi@192.168.1.175                                  │
     │   • SSH compression : ✔                                            │
     │   • SSH-browser     : ✔                                            │
     │   • X11-forwarding  : ✔  (remote display is forwarded through SSH) │
     │   • DISPLAY         : ✔  (automatically set on remote server)      │
     │                                                                    │
     │ ➤ For more info, ctrl+click on help or visit our website           │
     └────────────────────────────────────────────────────────────────────┘

Linux raspberrypi 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Jan 11 19:55:43 2021

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

pi@raspberrypi:~ $ cd Arducampython/
pi@raspberrypi:~/Arducampython $ ls
build  camera_installer.egg-info  CMakeLists.txt  dist  LICENSE  README.md  setup.py  src  test
pi@raspberrypi:~/Arducampython $ cd ..
pi@raspberrypi:~ $ ls
Arducampython  Documents  firestarter  hexastorm_design  MIPI_Camera  Pictures  raspiraw   tmp     WiringPi
Desktop        Downloads  hexastorm    litex             Music        Public    Templates  Videos  wiringpi-latest.deb
pi@raspberrypi:~ $ cd MIPI_Camera/
pi@raspberrypi:~/MIPI_Camera $ ls
Jetson  README.md  RPI
pi@raspberrypi:~/MIPI_Camera $ cd RPI/
pi@raspberrypi:~/MIPI_Camera/RPI $ ls
1.jpg                  capture             capture_raw.c       list_format              ov9281_external_trigger.c  preview_setMode.c     read_write_sensor_reg    video2stdout.c
2.jpg                  capture2opencv      cvui.h              list_format.c            preview.c                  python                read_write_sensor_reg.c  video4cameras
2MPGlobalShuterDemo    capture2opencv.cpp  enable_i2c_vc.sh    Makefile                 preview-camera0            qrcode_detection      stereo_depth_demo        video4cameras.c
2MPGlobalShuterDemo.c  capture.c           images              mode0.jpg                preview-camera0.c          qrcode_detection.cpp  test.h264                video.c
arducam_mipicamera.h   capture-dualcam     ISP                 opencvGui                preview-dualcam            raw_callback          utils                    yuv_callback
arducamstill           capture-dualcam.c   lens_shading_table  opencvGui.cpp            preview-dualcam.c          raw_callback.c        video                    yuv_callback.c
arducamstill.c         capture_raw         lib                 ov9281_external_trigger  preview_resolution.c       README.md             video2stdout
pi@raspberrypi:~/MIPI_Camera/RPI $ cd utils/
pi@raspberrypi:~/MIPI_Camera/RPI/utils $ ls
camera_i2c  mipi_raw10_to_jpg.py  mono_to_jpg.py  rpi3-gpiovirtbuf
pi@raspberrypi:~/MIPI_Camera/RPI/utils $ ./camera_i2c
setting GPIO for board revsion: d03114
Raspberry Pi3B / Pi3B+ / 3A / 4B(1G/2G/4G)
Set state of 133 to 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
pi@raspberrypi:~/MIPI_Camera/RPI/utils $ ./camera_i2c
setting GPIO for board revsion: d03114
Raspberry Pi3B / Pi3B+ / 3A / 4B(1G/2G/4G)
Set state of 133 to 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: 60 -- -- -- -- -- -- -- -- -- -- -- 6c -- -- --
70: 70 -- -- -- -- -- -- --
pi@raspberrypi:~/MIPI_Camera/RPI/utils $ vim /boot/config.txt
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

```
# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on
dtoverlay=spi0-1cs
dtoverlay=spi1-1cs,cs0_pin=7

dtparam=i2c_vc=on
# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

Network error: Connection timed out

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Session stopped
    - Press <return> to exit tab
    - Press R to restart session
    - Press S to save terminal output to file
     ┌────────────────────────────────────────────────────────────────────┐
     │                        • MobaXterm 20.6 •                          │
     │            (SSH client, X-server and networking tools)             │
     │                                                                    │
     │ ➤ SSH session to pi@192.168.1.175                                  │
     │   • SSH compression : ✔                                            │
     │   • SSH-browser     : ✔                                            │
     │   • X11-forwarding  : ✔  (remote display is forwarded through SSH) │
     │   • DISPLAY         : ✔  (automatically set on remote server)      │
     │                                                                    │
     │ ➤ For more info, ctrl+click on help or visit our website           │
     └────────────────────────────────────────────────────────────────────┘

Linux raspberrypi 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Jan 11 19:55:43 2021

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

pi@raspberrypi:~ $ cd Arducampython/
pi@raspberrypi:~/Arducampython $ ls
build  camera_installer.egg-info  CMakeLists.txt  dist  LICENSE  README.md  setup.py  src  test
pi@raspberrypi:~/Arducampython $ cd ..
pi@raspberrypi:~ $ ls
Arducampython  Documents  firestarter  hexastorm_design  MIPI_Camera  Pictures  raspiraw   tmp     WiringPi
Desktop        Downloads  hexastorm    litex             Music        Public    Templates  Videos  wiringpi-latest.deb
pi@raspberrypi:~ $ cd MIPI_Camera/
pi@raspberrypi:~/MIPI_Camera $ ls
Jetson  README.md  RPI
pi@raspberrypi:~/MIPI_Camera $ cd RPI/
pi@raspberrypi:~/MIPI_Camera/RPI $ ls
1.jpg                  capture             capture_raw.c       list_format              ov9281_external_trigger.c  preview_setMode.c     read_write_sensor_reg    video2stdout.c
2.jpg                  capture2opencv      cvui.h              list_format.c            preview.c                  python                read_write_sensor_reg.c  video4cameras
2MPGlobalShuterDemo    capture2opencv.cpp  enable_i2c_vc.sh    Makefile                 preview-camera0            qrcode_detection      stereo_depth_demo        video4cameras.c
2MPGlobalShuterDemo.c  capture.c           images              mode0.jpg                preview-camera0.c          qrcode_detection.cpp  test.h264                video.c
arducam_mipicamera.h   capture-dualcam     ISP                 opencvGui                preview-dualcam            raw_callback          utils                    yuv_callback
arducamstill           capture-dualcam.c   lens_shading_table  opencvGui.cpp            preview-dualcam.c          raw_callback.c        video                    yuv_callback.c
arducamstill.c         capture_raw         lib                 ov9281_external_trigger  preview_resolution.c       README.md             video2stdout
pi@raspberrypi:~/MIPI_Camera/RPI $ cd utils/
pi@raspberrypi:~/MIPI_Camera/RPI/utils $ ls
camera_i2c  mipi_raw10_to_jpg.py  mono_to_jpg.py  rpi3-gpiovirtbuf
pi@raspberrypi:~/MIPI_Camera/RPI/utils $ ./camera_i2c
setting GPIO for board revsion: d03114
Raspberry Pi3B / Pi3B+ / 3A / 4B(1G/2G/4G)
Set state of 133 to 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
pi@raspberrypi:~/MIPI_Camera/RPI/utils $ ./camera_i2c
setting GPIO for board revsion: d03114
Raspberry Pi3B / Pi3B+ / 3A / 4B(1G/2G/4G)
Set state of 133 to 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: 60 -- -- -- -- -- -- -- -- -- -- -- 6c -- -- --
70: 70 -- -- -- -- -- -- --
pi@raspberrypi:~/MIPI_Camera/RPI/utils $ vim /boot/config.txt

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on
dtoverlay=spi0-1cs
dtoverlay=spi1-1cs,cs0_pin=7

dtparam=i2c_vc=on
# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
start_x=1
gpu_mem=300      
```

**Comment by glddiv** [comment]
Hi @hstarmans 
We tested it, but did not reproduce your problem.
![ov2311](https://user-images.githubusercontent.com/24386338/104392999-55e14900-557e-11eb-94f4-12642a93e970.png)

Regarding the modification of Wiringpi you mentioned, there are known issues with Wiringpi on PI4, but we only need to upgrade Wiringpi to the latest.
![gpio_version](https://user-images.githubusercontent.com/24386338/104393024-65f92880-557e-11eb-8d70-a5adb4d298e6.png)

Can you tell me your system version? Not sure if this is related to the system version.

**Comment by hstarmans** [comment]
I upgraded the repo to the latest commit, installed the new binary and now It is fixed
```
commit 7f75cf1e0f870ba9eb567d71c5e09702b8a9f395 (HEAD -> master, origin/master, origin/HEAD)
Author: UCTRONICS <avahe@uctronics.com>
Date:   Wed Jan 13 09:05:18 2021 +0800

    Fix Ethernet problems
```
I am using
```
gpio version: 2.60
Copyright (c) 2012-2018 Gordon Henderson
This is free software with ABSOLUTELY NO WARRANTY.
For details type: gpio -warranty

Raspberry Pi Details:
  Type: Pi 4B, Revision: 04, Memory: 8192MB, Maker: Sony 
  * Device tree is enabled.
  *--> Raspberry Pi 4 Model B Rev 1.4
  * This Raspberry Pi supports user-level GPIO access.
```
Anyhow, thanks!
